# eel起動オプション
eel:
  # モード:
  ## chrome: Chromeブラウザとして起動, chrome-app: Chromeアプリとして起動
  mode: chrome-app

  # ローカルポート:
  ## Eelアプリケーションの実行ポート（localhost:XXXX）: 0を指定すると空いているポートを自動的に使う
  port: 0

  # Window位置:
  ## 起動時のWindow位置をPythonTuple形式 (x, y) で指定
  # position: !!python/tuple [0,0]
  
  # Windowサイズ:
  ## 起動時のWindowサイズをPythonTuple形式 (width, height) で指定
  size: !!python/tuple [800,600]
